require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Override Firebase SDK Version
$FirebaseSDKVersion = '6.34.0'

platform :ios, '12.0'

abstract_target 'CommonPods' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  # Pods for MentalHealthApp
  pod 'react-native-twilio-video-webrtc', path: '../node_modules/react-native-twilio-video-webrtc'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  pod 'Stripe', '~> 14.0.0'

  # Install additional dependencies
  pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'

  pod 'Firebase/Analytics'

  target 'MentalHealthAppTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
  
  target 'Marpe Release'
  target 'Marpe Dev'
    
end

# target 'MentalHealthApp-tvOS' do
#   # Pods for MentalHealthApp-tvOS

#   target 'MentalHealthApp-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
# end
