export const states = [
  { value: 'I0', label: 'Aberconwy and Colwyn (I0)' },
  { value: 'I1', label: 'Aberdeen City (I1)' },
  { value: 'I2', label: 'Aberdeenshire (I2)' },
  { value: 'I3', label: 'Anglesey (I3)' },
  { value: 'I4', label: 'Angus (I4)' },
  { value: 'I5', label: 'Antrim (I5)' },
  { value: 'I6', label: 'Argyll and Bute (I6)' },
  { value: 'I7', label: 'Armagh (I7)' },
  { value: 'I8', label: 'Avon (I8)' },
  { value: 'I9', label: 'Ayrshire (I9)' },
  { value: 'IB', label: 'Bath and NE Somerset (IB)' },
  { value: 'IC', label: 'Bedfordshire (IC)' },
  { value: 'IE', label: 'Belfast (IE)' },
  { value: 'IF', label: 'Berkshire (IF)' },
  { value: 'IG', label: 'Berwickshire (IG)' },
  { value: 'IH', label: 'BFPO (IH)' },
  { value: 'II', label: 'Blaenau Gwent (II)' },
  { value: 'IJ', label: 'Buckinghamshire (IJ)' },
  { value: 'IK', label: 'Caernarfonshire (IK)' },
  { value: 'IM', label: 'Caerphilly (IM)' },
  { value: 'IO', label: 'Caithness (IO)' },
  { value: 'IP', label: 'Cambridgeshire (IP)' },
  { value: 'IQ', label: 'Cardiff (IQ)' },
  { value: 'IR', label: 'Cardiganshire (IR)' },
  { value: 'IS', label: 'Carmarthenshire (IS)' },
  { value: 'IT', label: 'Ceredigion (IT)' },
  { value: 'IU', label: 'Channel Islands (IU)' },
  { value: 'IV', label: 'Cheshire (IV)' },
  { value: 'IW', label: 'City of Bristol (IW)' },
  { value: 'IX', label: 'Clackmannanshire (IX)' },
  { value: 'IY', label: 'Clwyd (IY)' },
  { value: 'IZ', label: 'Conwy (IZ)' },
  { value: 'J0', label: 'Cornwall/Scilly (J0)' },
  { value: 'J1', label: 'Cumbria (J1)' },
  { value: 'J2', label: 'Denbighshire (J2)' },
  { value: 'J3', label: 'Derbyshire (J3)' },
  { value: 'J4', label: 'Derry/Londonderry (J4)' },
  { value: 'J5', label: 'Devon (J5)' },
  { value: 'J6', label: 'Dorset (J6)' },
  { value: 'J7', label: 'Down (J7)' },
  { value: 'J8', label: 'Dumfries and Galloway (J8)' },
  { value: 'J9', label: 'Dunbartonshire (J9)' },
  { value: 'JA', label: 'Dundee (JA)' },
  { value: 'JB', label: 'Durham (JB)' },
  { value: 'JC', label: 'Dyfed (JC)' },
  { value: 'JD', label: 'East Ayrshire (JD)' },
  { value: 'JE', label: 'East Dunbartonshire (JE)' },
  { value: 'JF', label: 'East Lothian (JF)' },
  { value: 'JG', label: 'East Renfrewshire (JG)' },
  { value: 'JH', label: 'East Riding Yorkshire (JH)' },
  { value: 'JI', label: 'East Sussex (JI)' },
  { value: 'JJ', label: 'Edinburgh (JJ)' },
  { value: 'JK', label: 'England (JK)' },
  { value: 'JL', label: 'Essex (JL)' },
  { value: 'JM', label: 'Falkirk (JM)' },
  { value: 'JN', label: 'Fermanagh (JN)' },
  { value: 'JO', label: 'Fife (JO)' },
  { value: 'JP', label: 'Flintshire (JP)' },
  { value: 'JQ', label: 'Glasgow (JQ)' },
  { value: 'JR', label: 'Gloucestershire (JR)' },
  { value: 'JS', label: 'Greater London (JS)' },
  { value: 'JT', label: 'Greater Manchester (JT)' },
  { value: 'JU', label: 'Gwent (JU)' },
  { value: 'JV', label: 'Gwynedd (JV)' },
  { value: 'JW', label: 'Hampshire (JW)' },
  { value: 'JX', label: 'Hartlepool (JX)' },
  { value: 'HAW', label: 'Hereford and Worcester (HAW)' },
  { value: 'JY', label: 'Hertfordshire (JY)' },
  { value: 'JZ', label: 'Highlands (JZ)' },
  { value: 'K0', label: 'Inverclyde (K0)' },
  { value: 'K1', label: 'Inverness-Shire (K1)' },
  { value: 'K2', label: 'Isle of Man (K2)' },
  { value: 'K3', label: 'Isle of Wight (K3)' },
  { value: 'K4', label: 'Kent (K4)' },
  { value: 'K5', label: 'Kincardinshire (K5)' },
  { value: 'K6', label: 'Kingston Upon Hull (K6)' },
  { value: 'K7', label: 'Kinross-Shire (K7)' },
  { value: 'K8', label: 'Kirklees (K8)' },
  { value: 'K9', label: 'Lanarkshire (K9)' },
  { value: 'KA', label: 'Lancashire (KA)' },
  { value: 'KB', label: 'Leicestershire (KB)' },
  { value: 'KC', label: 'Lincolnshire (KC)' },
  { value: 'KD', label: 'Londonderry (KD)' },
  { value: 'KE', label: 'Merseyside (KE)' },
  { value: 'KF', label: 'Merthyr Tydfil (KF)' },
  { value: 'KG', label: 'Mid Glamorgan (KG)' },
  { value: 'KI', label: 'Mid Lothian (KI)' },
  { value: 'KH', label: 'Middlesex (KH)' },
  { value: 'KJ', label: 'Monmouthshire (KJ)' },
  { value: 'KK', label: 'Moray (KK)' },
  { value: 'KL', label: 'Neath \u0026 Port Talbot (KL)' },
  { value: 'KM', label: 'Newport (KM)' },
  { value: 'KN', label: 'Norfolk (KN)' },
  { value: 'KP', label: 'North Ayrshire (KP)' },
  { value: 'KQ', label: 'North East Lincolnshire (KQ)' },
  { value: 'KR', label: 'North Lanarkshire (KR)' },
  { value: 'KT', label: 'North Lincolnshire (KT)' },
  { value: 'KU', label: 'North Somerset (KU)' },
  { value: 'KV', label: 'North Yorkshire (KV)' },
  { value: 'KO', label: 'Northamptonshire (KO)' },
  { value: 'KW', label: 'Northern Ireland (KW)' },
  { value: 'KX', label: 'Northumberland (KX)' },
  { value: 'KZ', label: 'Nottinghamshire (KZ)' },
  { value: 'L0', label: 'Orkney and Shetland Isles (L0)' },
  { value: 'L1', label: 'Oxfordshire (L1)' },
  { value: 'L2', label: 'Pembrokeshire (L2)' },
  { value: 'L3', label: 'Perth and Kinross (L3)' },
  { value: 'L4', label: 'Powys (L4)' },
  { value: 'L5', label: 'Redcar and Cleveland (L5)' },
  { value: 'L6', label: 'Renfrewshire (L6)' },
  { value: 'L7', label: 'Rhonda Cynon Taff (L7)' },
  { value: 'L8', label: 'Rutland (L8)' },
  { value: 'L9', label: 'Scottish Borders (L9)' },
  { value: 'LB', label: 'Shetland (LB)' },
  { value: 'LC', label: 'Shropshire (LC)' },
  { value: 'LD', label: 'Somerset (LD)' },
  { value: 'LE', label: 'South Ayrshire (LE)' },
  { value: 'LF', label: 'South Glamorgan (LF)' },
  { value: 'LG', label: 'South Gloucesteshire (LG)' },
  { value: 'LH', label: 'South Lanarkshire (LH)' },
  { value: 'LI', label: 'South Yorkshire (LI)' },
  { value: 'LJ', label: 'Staffordshire (LJ)' },
  { value: 'LK', label: 'Stirling (LK)' },
  { value: 'LL', label: 'Stockton On Tees (LL)' },
  { value: 'LM', label: 'Suffolk (LM)' },
  { value: 'LN', label: 'Surrey (LN)' },
  { value: 'LO', label: 'Swansea (LO)' },
  { value: 'LP', label: 'Torfaen (LP)' },
  { value: 'LQ', label: 'Tyne and Wear (LQ)' },
  { value: 'LR', label: 'Tyrone (LR)' },
  { value: 'LS', label: 'Vale Of Glamorgan (LS)' },
  { value: 'LT', label: 'Wales (LT)' },
  { value: 'LU', label: 'Warwickshire (LU)' },
  { value: 'LV', label: 'West Berkshire (LV)' },
  { value: 'LW', label: 'West Dunbartonshire (LW)' },
  { value: 'LX', label: 'West Glamorgan (LX)' },
  { value: 'LY', label: 'West Lothian (LY)' },
  { value: 'LZ', label: 'West Midlands (LZ)' },
  { value: 'M0', label: 'West Sussex (M0)' },
  { value: 'M1', label: 'West Yorkshire (M1)' },
  { value: 'M2', label: 'Western Isles (M2)' },
  { value: 'M3', label: 'Wiltshire (M3)' },
  { value: 'M4', label: 'Wirral (M4)' },
  { value: 'M5', label: 'Worcestershire (M5)' },
  { value: 'M6', label: 'Wrexham (M6)' },
  { value: 'M7', label: 'York (M7)' },
];
